/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lp11;

import javax.swing.JOptionPane;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Filhas
 */
public class Form_Impressora extends javax.swing.JFrame {

    /**
     * Creates new form Form_Impressora
     */
    public Form_Impressora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblImprimirpapel = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        lblScannerpapel = new javax.swing.JLabel();
        btnScanear = new javax.swing.JButton();
        lblCopiaspapel = new javax.swing.JLabel();
        btnCopiar = new javax.swing.JButton();
        lblAlimentartinta = new javax.swing.JLabel();
        btnCarregar = new javax.swing.JRadioButton();
        btnMaistarde = new javax.swing.JRadioButton();
        lblAlimentarpapel = new javax.swing.JLabel();
        btnLembrar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextamanho = new javax.swing.JTextField();
        jTextCor = new javax.swing.JTextField();
        jTextMaterial = new javax.swing.JTextField();
        jTextPeso = new javax.swing.JTextField();
        jTextModelo = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImprimirpapel.setText("Para imprimir clique no notão abaixo");

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        lblScannerpapel.setText("Clique abaixo para fazer scanner");

        btnScanear.setText("Scannear");
        btnScanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScanearActionPerformed(evt);
            }
        });

        lblCopiaspapel.setText("Clique abaixo para fazer cópias:");

        btnCopiar.setText("Copiar");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        lblAlimentartinta.setText("Carregue a tinta do seu dispositivo");

        buttonGroup1.add(btnCarregar);
        btnCarregar.setText("Carregar agora");
        btnCarregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarregarMouseClicked(evt);
            }
        });
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnMaistarde);
        btnMaistarde.setText("Mais tarde");
        btnMaistarde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaistardeMouseClicked(evt);
            }
        });
        btnMaistarde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaistardeActionPerformed(evt);
            }
        });

        lblAlimentarpapel.setText("Alimente com papel seu dispositivo");

        btnLembrar.setText("Lembrar mais tarde");
        btnLembrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLembrarMouseClicked(evt);
            }
        });

        jLabel1.setText("Informações da Impressora:");

        jLabel2.setText("Tamanho:");

        jLabel3.setText("Cor:");

        jLabel4.setText("Material:");

        jLabel5.setText("Peso:");

        jLabel6.setText("Modelo:");

        jTextamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextamanhoActionPerformed(evt);
            }
        });

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblImprimirpapel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnImprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnScanear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCopiaspapel)
                            .addComponent(lblScannerpapel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlimentarpapel)
                            .addComponent(btnMaistarde)
                            .addComponent(btnCarregar)
                            .addComponent(lblAlimentartinta)
                            .addComponent(btnLembrar))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(109, 109, 109))))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnCopiar)
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextamanho)
                            .addComponent(jTextCor, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextMaterial)
                            .addComponent(jTextPeso)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bntSalvar)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImprimirpapel)
                    .addComponent(lblAlimentartinta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnCarregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaistarde)
                .addGap(16, 16, 16)
                .addComponent(lblScannerpapel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnScanear)
                        .addGap(31, 31, 31)
                        .addComponent(lblCopiaspapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCopiar)
                            .addComponent(jLabel2)
                            .addComponent(jTextamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblAlimentarpapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLembrar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bntSalvar)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        // TODO add your handling code here:
        btnCopiar.setText("Realizando cópia(s)");
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        btnImprimir.setText("Imprimindo...aguarde");
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnScanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScanearActionPerformed
        // TODO add your handling code here:
        btnScanear.setText("Scanneando o(s) documento(s)");
    }//GEN-LAST:event_btnScanearActionPerformed

    private void btnCarregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarregarMouseClicked
        // TODO add your handling code here:
        if (btnCarregar.isSelected())
            JOptionPane.showMessageDialog(null, "A impressora está pausada aguardando você colocar papéis.");
    }//GEN-LAST:event_btnCarregarMouseClicked

    private void btnMaistardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaistardeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaistardeActionPerformed

    private void btnMaistardeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaistardeMouseClicked
        // TODO add your handling code here:
        if (btnMaistarde.isSelected())
            JOptionPane.showMessageDialog(null, "Carregar mais tarde");
    }//GEN-LAST:event_btnMaistardeMouseClicked

    private void btnLembrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLembrarMouseClicked
        // TODO add your handling code here:
        if (btnLembrar.isSelected())
            JOptionPane.showMessageDialog(null, "Lembrete adiado para 1 hora, contando a partir de agora");
    }//GEN-LAST:event_btnLembrarMouseClicked

    private void jTextamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextamanhoActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        // TODO add your handling code here:
        int retornodaConfirmacao = JOptionPane.showConfirmDialog(null,"O Usuário deseja guardar os dados inseridos?");
        System.out.println(retornodaConfirmacao);
        
        jTextamanho.getText();
        jTextCor.getText();
        jTextMaterial.getText();
        jTextPeso.getText();
        jTextModelo.getText();
        String mensagem = "Iremos salvar essas informações em arquivo:\n"
                + "Tamanho:"+jTextamanho.getText()+"\n"
                +"Cor:"+jTextCor.getText()+"\n"
                +"Material:"+jTextMaterial.getText()+"\n"
                +"Peso:"+jTextPeso.getText()+"\n"
                +"Modelo:"+jTextModelo.getText();
        
        JOptionPane.showMessageDialog(null, mensagem);
        
        try {
            PrintWriter outFile = new PrintWriter("nomeDoArquivo.csv");
            outFile.println("Tamanho:"+jTextamanho.getText());
            outFile.println("Cor:"+jTextCor.getText());
            outFile.println("Peso:"+jTextPeso.getText());
            outFile.println("Peso:"+jTextPeso.getText());
            outFile.println("Modelo:"+jTextModelo.getText());
            JOptionPane.showMessageDialog(null, "Arquivo salvo com sucesso");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Arquivo não encontrado");
        }

    }//GEN-LAST:event_bntSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Impressora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Impressora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Impressora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Impressora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Impressora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalvar;
    private javax.swing.JRadioButton btnCarregar;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JRadioButton btnLembrar;
    private javax.swing.JRadioButton btnMaistarde;
    private javax.swing.JButton btnScanear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextCor;
    private javax.swing.JTextField jTextMaterial;
    private javax.swing.JTextField jTextModelo;
    private javax.swing.JTextField jTextPeso;
    private javax.swing.JTextField jTextamanho;
    private javax.swing.JLabel lblAlimentarpapel;
    private javax.swing.JLabel lblAlimentartinta;
    private javax.swing.JLabel lblCopiaspapel;
    private javax.swing.JLabel lblImprimirpapel;
    private javax.swing.JLabel lblScannerpapel;
    // End of variables declaration//GEN-END:variables
}
